create table maestro_db (
    id uuid primary key default gen_random_uuid(),
    num_lote varchar null,
    tecnico varchar null,
    orden varchar null,
    tip_orden varchar null,
    nic varchar null,
    zona varchar null,
    departamento varchar null,
    municipio varchar null,
    corregimiento varchar null,
    localidad varchar null,
    tip_via varchar null,
    nom_calle varchar null,
    duplicador varchar null,
    num_puerta int null,
    direccion varchar null,
    dir_referencia varchar null,
    nombre_cliente varchar null,
    tarifa varchar null,
    deuda_vencida decimal null,
    facturas_vencidas int null,
    num_medidor varchar null,
    marca_medidor varchar null,
    antiguedad int null,
    estado varchar null,
    ct_gestor varchar null,
    comentario text null,
    tipo_suspension_scr varchar null,
    estado_del_servicio varchar null,
    deuda_hoy decimal null,
    fecha_de_vencimiento int null,
    facturas_vencidas_2 int null,
    nombre_del_cliente_2 varchar null,
    tarifa_2 varchar null,
    marca_medidor_2 varchar null,
    numero_de_medidor varchar null,
    municipio_2 varchar null,
    corregimiento_2 varchar null,
    barrio varchar null,
    direccion_2 varchar null,
    multifamiliar int null,
    material_en_bodega varchar null,
    maestro_zona varchar null,
    priorizacion int null,
    exclusiones_temporal varchar null,
    tipo_brigada varchar null,
    cluster varchar null,
    eliminado boolean default false,
    fecha_registro timestamptz default current_timestamp
);

create table pmu_priorizacion_cliente (
    id uuid primary key default gen_random_uuid(),
    prioridad int not null,
    cuenta varchar not null,
    numero_os varchar not null,
    tipo_orden varchar not null,
    tipo_brigada varchar not null,
    tipo_actividad varchar not null,
    fecha_asignacion_cliente int not null,
    eliminado boolean null default false,
    fecha_registro timestamptz null default current_timestamp
);

create table balanza (
    id uuid primary key default gen_random_uuid(),
    zona varchar not null,
    cuenta varchar null,
    producto varchar null,
    nombre_cliente varchar null,
    ejecutivo_cuenta varchar null,
    direccion_cliente varchar null,
    territorial varchar null,
    municipio varchar null,
    categoria varchar null,
    subcategoria varchar null,
    fecha_facturacion date null,
    fecha_vencimiento date null,
    facturado_energia decimal null,
    facturado_irregularidades decimal null,
    facturado_sin_irr decimal null,
    facturado_terceros decimal null,
    con_pago varchar null,
    fecha_pago date null,
    recaudo_energia decimal null,
    recaudo_corriente decimal null,
    recaudo_cartera decimal null,
    recaudo_0_30 decimal null,
    recaudo_energia_irr decimal null,
    recaudo_sin_irr decimal null,
    recaudo_terceros decimal null,
    suma_de_deuda_energia_bdef decimal null,
    suma_de_deuda_total decimal null,
    suma_de_facturas decimal null,
    fecha_registro timestamp null default current_timestamp
);

create table control_op (
    id uuid primary key default gen_random_uuid(),
    periodo varchar null,
    cuenta varchar null,
    producto varchar null,
    nif varchar null,
    suma_de_multifamiliar decimal null,
    nombre_multifamiliar varchar null,
    estado_cuenta varchar null,
    estado_corte varchar null,
    tipo_medicion varchar null,
    suma_de_medido decimal null,
    id_medidor varchar null,
    marca_medidor varchar null,
    tipo_medida varchar null,
    id_transformador varchar null,
    circuito varchar null,
    ciclo varchar null,
    id_ciclo varchar null,
    itinerario varchar null,
    gestor_ejecutivo varchar null,
    pyme varchar null,
    padre_hijo varchar null,
    categoria varchar null,
    tarifa varchar null,
    actividad_economica varchar null,
    tipo_predio varchar null,
    tipo_mercado varchar null,
    suma_de_id_zona varchar null,
    linea_estrategica varchar null,
    nombre_cliente varchar null,
    telefono varchar null,
    direccion_cliente varchar null,
    territorial varchar null,
    zona varchar null,
    departamento varchar null,
    municipio varchar null,
    corregimiento varchar null,
    barrio varchar null,
    id_barrio varchar null,
    suma_de_facturado decimal null,
    f_lectura varchar null,
    f_lectura_mesant varchar null,
    bdef_dias_consumo int null,
    bdef_mesant_dias_consumo int null,
    fecha_facturacion varchar null,
    fecha_facturacion_mesant varchar null,
    suma_de_factura_vencida decimal null,
    fecha_vencimiento varchar null,
    fecha_vencimiento_mesant varchar null,
    consumo_kwh decimal null,
    consumo_kwh_mesant decimal null,
    indicador_facturacion varchar null,
    observacion_lectura varchar null,
    indicador_facturacion_mesant varchar null,
    observacion_lectura_mesant varchar null,
    valor_facturado_sin_irreg decimal null,
    valor_facturado_sin_irreg_mesant decimal null,
    recaudo_energia_sin_irr decimal null,
    recaudo_corriente decimal null,
    recaudo_cartera decimal null,
    pendiente_de_cobro decimal null,
    pendiente_de_cobro_cte decimal null,
    recaudo_sin_irreg_mesant decimal null,
    recaudo_energia_promedio decimal null,
    suma_de_recaudo_acuerdos decimal null,
    suma_de_con_pago decimal null,
    f_pago varchar null,
    banco_pago varchar null,
    pago_mesant varchar null,
    suma_de_cant_pagos_6meses int null,
    suma_de_cant_pagos_12meses int null,
    segmentacion varchar null,
    rfm_recargado varchar null,
    rfm varchar null,
    f_aplicacion_pago varchar null,
    periodo_ultimo_pago varchar null,
    suma_de_moroso decimal null,
    suma_de_moroso_mesant decimal null,
    deuda_total decimal null,
    deuda_hoy decimal null,
    suma_de_deuda_terceros decimal null,
    deuda_hoy_mesant decimal null,
    rango_cant_fact varchar null,
    cantidad_facturas int null,
    rango_cant_fact_mesant varchar null,
    suma_de_cantidad_facturas_mesant int null,
    suma_de_cliente_organico decimal null,
    deuda_30 decimal null,
    deuda_60 decimal null,
    deuda_90 decimal null,
    deuda_mas_90 decimal null,
    suma_de_edad_deuda int null,
    deuda_reclamada decimal null,
    deuda_financiada decimal null,
    prescrita varchar null,
    saldo_a_favor decimal null,
    valor_facturado_irregularidad decimal null,
    valor_facturado_irregularidad_mesant decimal null,
    recaudo_irregularidad decimal null,
    recaudo_irregularidad_mesant decimal null,
    plan_gestion_cobro varchar null,
    gestion_scr varchar null,
    gestion_persuasivo varchar null,
    gestion_scr_centralizada varchar null,
    rango_facturado varchar null,
    rango_facturado_mesant varchar null,
    rango_deuda varchar null,
    rango_consumo_kwh varchar null,
    rango_consumo_kwh_mesant varchar null,
    protegido varchar null,
    demandado varchar null,
    anomalia_scr varchar null,
    tipo_suspension varchar null,
    segmento_oficial varchar null,
    alertas varchar null,
    fecha_registro timestamp null default current_timestamp
);

create table asignacion_control (
    id uuid primary key default gen_random_uuid(),
    num_lote varchar null,
    tecnico varchar null,
    orden varchar null,
    tip_orden varchar null,
    nic varchar null,
    zona varchar null,
    departamento varchar null,
    municipio varchar null,
    corregimiento varchar null,
    localidad varchar null,
    tip_via varchar null,
    nom_calle varchar null,
    duplicador varchar null,
    num_puerta int null,
    direccion varchar null,
    dir_referencia varchar null,
    nombre_cliente varchar null,
    tarifa varchar null,
    deuda_vencida decimal null,
    facturas_vencidas int null,
    num_medidor varchar null,
    marca_medidor varchar null,
    antiguedad int null,
    estado varchar null,
    ct_gestor varchar null,
    comentario text null,
    tipo_suspension_scr varchar null,
    estado_del_servicio varchar null,
    fecha_registro timestamp null default current_timestamp
);
